// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateOrderInput struct {
	UserID      int     `json:"user_id"`
	ProductName string  `json:"product_name"`
	Quantity    int     `json:"quantity"`
	Price       float64 `json:"price"`
}

type CreateUserInput struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

type Mutation struct {
}

type Notification struct {
	ID        string `json:"id"`
	PaymentID int    `json:"payment_id"`
	OrderID   int    `json:"order_id"`
	Message   string `json:"message"`
	Status    string `json:"status"`
	CreatedAt string `json:"created_at"`
}

type Order struct {
	ID          string  `json:"id"`
	UserID      int     `json:"user_id"`
	ProductName string  `json:"product_name"`
	Quantity    int     `json:"quantity"`
	Price       float64 `json:"price"`
	Status      string  `json:"status"`
	CreatedAt   string  `json:"created_at"`
}

type OrderSummary struct {
	Order         *Order          `json:"order,omitempty"`
	User          *User           `json:"user,omitempty"`
	Payment       *Payment        `json:"payment,omitempty"`
	Notifications []*Notification `json:"notifications,omitempty"`
}

type Payment struct {
	ID            string  `json:"id"`
	OrderID       int     `json:"order_id"`
	UserID        int     `json:"user_id"`
	Amount        float64 `json:"amount"`
	Status        string  `json:"status"`
	PaymentMethod string  `json:"payment_method"`
	CreatedAt     string  `json:"created_at"`
}

type Query struct {
}

type User struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Email     string `json:"email"`
	CreatedAt string `json:"created_at"`
}
